### ISSUE TITLE
Add a Real Lexer

### ISSUE THREAD

**Issue by jessicahayley** [jessicahayley/bondage.js#9]
Right now we're using hacky string manipulation to check for things like links, a lexer would allow this to be cleaner and allow us to implement more complex logic like shortcut options

**Comment by jessicahayley** [comment]
YarnSpinner's documentation on the language structure: https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Usage.md

**Comment by konistehrad** [comment]
I like the new YarnSpinner approach to this, which is based on state transitions. This could probably be adapted to JS trivially, as we're really just talking about dictionaries and regex's: https://github.com/thesecretlab/YarnSpinner/blob/master/YarnSpinner/Lexer.cs

**Comment by jessicahayley** [comment]
This might be handy: http://zaa.ch/jison/

**Comment by jessicahayley** [comment]
I'm trying out jison in the add-lexer branch https://github.com/jessicahayley/bondage.js/commits/add-lexer

**Comment by jessicahayley** [comment]
#11 :D :D :D

**Comment by jessicahayley** [comment]
The lexer is greatly inspired by yarnspinner's, and the parser uses jison to run the results through a grammar. Seems to work really well, and adding new syntax is super easy (see: 92043f9661e0593425f2178de4023aa80c4f35a7)
